# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 13:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_favorite_promocode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='Expiring_Date',
            new_name='expiring_date',
        ),
        migrations.AddField(
            model_name='promocode',
            name='code_percentage',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AddField(
            model_name='promocode',
            name='fixed_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
