# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180523_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='fixed_price',
        ),
    ]
