# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 13:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_promocode_fixed_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='code_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxLengthValidator(100)]),
            preserve_default=False,
        ),
    ]
