# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180523_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='code_percentage',
        ),
    ]
