# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 16:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20180709_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='code_percentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
