# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20180827_1748'),
        ('accounts', '0003_auto_20180731_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wish_list',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
    ]
