# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_promocode_code_percentage'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.ManyToManyField(to='product.PromoCode'),
        ),
    ]
