# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180726_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promocode',
            field=models.ManyToManyField(blank=True, null=True, to='product.PromoCode'),
        ),
    ]
