# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20180912_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_item',
            field=models.ManyToManyField(related_name='product_item', to='product.Product'),
        ),
    ]
